INSERT INTO games (title, on_sale) VALUES ('Counter-Strike 2', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Apex Legends™', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('PUBG: BATTLEGROUNDS', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Palworld', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Team Fortress 2', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Call of Duty®', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('New World: Aeternum', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Black Myth: Wukong', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Grand Theft Auto V Legacy', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Left 4 Dead 2', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Unturned', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Lost Ark', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('War Thunder', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Monster Hunter Wilds', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('HELLDIVERS™ 2', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Warframe', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('ELDEN RING', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Terraria', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Path of Exile 2', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Wallpaper Engine', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Baldur''s Gate 3', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Brawlhalla', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Garry''s Mod', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Destiny 2', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Tom Clancy''s Rainbow Six® Siege X', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Rust', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('World of Warships', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('ARK: Survival Evolved', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Stardew Valley', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('The Forest', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('War Robots: Frontiers', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Path of Exile', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('PAYDAY 2', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Warface: Clutch', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Grand Theft Auto IV: Complete Edition', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Last Epoch', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Half-Life 2: Lost Coast', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Cyberpunk 2077', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Dead by Daylight', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Hogwarts Legacy', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('VRChat', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('The Witcher 3: Wild Hunt', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Among Us', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Fall Guys', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Borderlands 2', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Euro Truck Simulator 2', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Valheim', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Phasmophobia 恐鬼症', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Paladins®', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('NARAKA: BLADEPOINT', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Half-Life 2: Deathmatch', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Half-Life', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Monster Hunter: World', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Heroes & Generals', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Rocket League®', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Project Zomboid', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Lethal Company', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Red Dead Redemption 2', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Battlefield™ 2042', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Halo Infinite', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Raft', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('SMITE®', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('World of Tanks Blitz', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Counter-Strike', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Counter-Strike: Source', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Schedule I', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Ring of Elysium', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Portal', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('The Sims™ 4', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Black Squad', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Don''t Starve Together', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Dying Light', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Human Fall Flat', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('7 Days to Die', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Counter-Strike: Condition Zero', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('eFootball™', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Street Warriors Online', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Z1 Battle Royale', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Hunt: Showdown 1896', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Sekiro™: Shadows Die Twice - GOTY Edition', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('CyberCorp', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Half-Life 2', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Arma 3', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Sons Of The Forest', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Grim Dawn', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Cities: Skylines', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Mount & Blade II: Bannerlord', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Sid Meier''s Civilization® V', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Trove', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Sid Meier’s Civilization® VI', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Fallout 4', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Life is Strange 2', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Warhammer 40,000: Rogue Trader', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Battlefield™ V', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('R.E.P.O.', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('DayZ', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Satisfactory', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('NBA 2K20', false) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('Risk of Rain 2', true) ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title, on_sale) VALUES ('EA SPORTS™ FIFA 23', false) ON CONFLICT (title) DO NOTHING;