INSERT INTO genres (name) VALUES ('Action') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Adventure') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Animation & Modeling') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Casual') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Design & Illustration') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Early Access') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Free To Play') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Indie') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Massively Multiplayer') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Photo Editing') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('RPG') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Racing') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Simulation') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Sports') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Strategy') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Utilities') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Sandbox') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Rogue') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Shooter') ON CONFLICT (name) DO NOTHING;
INSERT INTO genres (name) VALUES ('Horror') ON CONFLICT (name) DO NOTHING;